# Generated by Django 3.1.2 on 2020-10-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
